### ISSUE TITLE
Wrap-up Checklist

### ISSUE THREAD

**Issue by philschanely** [SchanelyStudios/daytonave-web#58]
- [ ] Calendar default setup
- [x] Remove test pages
- [x] Remove unused/test images
- [ ] Set up previews
